[package]
name = "mygrid_pv"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
plotters = "0.3.7"
csv = "1.3.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

